---
- name: install base packages
  apt:
    state: present
    update_cache: yes
    cache_valid_time: 3600
    name:
      - curl
      - sudo
      - ctop
      - hstr
      - fzf
      - jq
      - tcpdump
      - ufw
      - vim
      - open-iscsi
      - golang-1.20

- name: set timezone to UTC
  timezone:
    name: UTC
