name: Deploy Injective
on:
  workflow_dispatch:
    inputs:
      ip:
        description: "IP address where you want to deploy injective."
        required: true
      node_name:
        description: "Name of the node (This will also become the moniker)"
        required: true
      network:
        description: "Network the node will run"
        type: choice
        options:
          - mainnet
          - testnet
        required: true
      version:
        description: App version
        required: true
      seeds:
        description: List of seed hosts, separated by comma
        required: true        
      peers:
        description: List of peristent peers, separated by comma
        required: true
      command:
        description: Docker-compose command to be executed 
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      
      - name: Create inventory
        run: |
          sed -i -e 's/<hosts>/${{ github.event.inputs.node_name }}/' ./ansible/inventory
          sed -i -e 's/<ip_address>/${{ github.event.inputs.ip }}/' ./ansible/inventory
